### ISSUE TITLE
Duplicate pages about upgrading

### ISSUE THREAD

**Issue by thomas-daniels** [haiwen/seafile-admin-docs#124]
I found two pages in the manual about upgrading Seafile that look very similar: https://manual.seafile.com/deploy/upgrade/ and https://manual.seafile.com/upgrade/upgrade/ . Aside from the introduction, the pages look identical, except that the latter link is probably more recent: it has higher version numbers in the examples, and links to upgrade notes up to 8.0.x (9.0.x is however still missing), whereas the former page just links to https://manual.seafile.com/deploy/upgrade_notes/ which seems to be quite outdated. It probably makes sense to make one page complete and fully up-to-date and remove the other one to avoid confusion, unless there is a difference between these pages that I'm missing and is not clarified.

**Comment by freeplant** [comment]
Thanks. It is fixed in https://github.com/haiwen/seafile-admin-docs/pull/125
