### ISSUE TITLE
Raspberry Pi server cannot be built

### ISSUE THREAD

**Issue by masiton** [haiwen/seafile-admin-docs#139]
Trying to install the flup tarball from dependencies results in error.

`pip install -t ~/dev/seahub_thirdpart/ /tmp/flup-1.0.2.tar.gz
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/flup-1.0.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-mrtmveot/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-mrtmveot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-nwtvhm6r
         cwd: /tmp/pip-req-build-mrtmveot/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-mrtmveot/setup.py", line 2, in <module>
        from ez_setup import use_setuptools
      File "/tmp/pip-req-build-mrtmveot/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    ----------------------------------------
WARNING: Discarding file:///tmp/flup-1.0.2.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

![2023-03-01_122223](https://user-images.githubusercontent.com/7767671/222125435-85b74af1-515c-48ce-8416-6506cda918f8.png)

**Comment by freeplant** [comment]
The building instruction has been updated.
