### ISSUE TITLE
Doc: ElasticSearch server

### ISSUE THREAD

**Issue by H4usi** [haiwen/seafile-admin-docs#167]
In the instructions, the scheme should not be mentioned in the examples for the Elasticsearch Host configuration (es_host) if it is not expected at this point. Also, the instructions completely lack any reference to the "scheme". 

https://manual.seafile.com/upgrade/upgrade_notes_for_10.0.x/
"es_host = **http{s}://**{es server IP}"

and missing scheme mentions: 
https://manual.seafile.com/deploy_pro/details_about_file_search/

**Comment by freeplant** [comment]
Thanks for reporting the issue. Changed in this PR: https://github.com/haiwen/seafile-admin-docs/pull/168/files
