### ISSUE TITLE
CONSISTENCY: double documentation

### ISSUE THREAD

**Issue by t-h2o** [haiwen/seafile-admin-docs#180]
# Two place for the same subject

Is it normal there is two documentation about `seaf-cli` ?

* https://manual.seafile.com/client/seafile_cli/
* https://help.seafile.com/syncing_client/linux-cli/

**Comment by feiniks** [comment]
Thanks for reporting the issue.  Fix in this pr https://github.com/haiwen/seafile-admin-docs/pull/181.
