### ISSUE TITLE
Missing dependencies in documentation for Ubuntu 20.04

### ISSUE THREAD

**Issue by bertvandepoel** [haiwen/seafile-admin-docs#26]
We just upgraded a server from Ubuntu 18.04 to Ubuntu 20.04 and noticed missing dependencies on python3-memcache and python3-mysqldb on https://github.com/haiwen/seafile-admin-docs/blob/master/manual/deploy/using_mysql.md . It's very well possible that this same problem also existed on 18.04 but that those packaged happened to be installed before.

We thought you may want to know!

**Comment by dada-dudu** [comment]
The relevant sections of the manual have been rewritten. As a part of the exercise, installation instructions for Ubuntu 20.04 were added. The issue should be solved.

**Comment by bertvandepoel** [comment]
Aren't the libraries I mentioned still missing?

**Comment by dada-dudu** [comment]
The two libraries that you mention are indeed missing. Good point.
On the other hand: I successfully deployed Seafile on Ubuntu 20.04 following these instructions to the letter.

**Comment by bertvandepoel** [comment]
Hmm, how strange. Maybe some of the other dependencies now bring them along? Could you check if they're installed and then "aptitude why" or something?

**Comment by dada-dudu** [comment]
I killed the test system. So I'd have to setup a new one. I would like to save this time. But believe me, I went to great lengths (=invested a lot of time) to make sure that the install instructions are all functional.

**Comment by freeplant** [comment]
python3-memcache is no longer needed. python3-memcache is replaced by pylibmc.

If you upgrade from a lower version, change your memcache settings to use pylibmc: https://manual.seafile.com/deploy/add_memcached/

**Comment by bertvandepoel** [comment]
I guess this issue is so old that it's no longer relevant and can be closed. I see that quite a few issues from 2021 and 2022 are still open on this repository and I wonder if they shouldn't be looked into @freeplant
