### ISSUE TITLE
seafile version in docker compose

### ISSUE THREAD

**Issue by vincentkersten** [haiwen/seafile-admin-docs#272]
Dear Haiwen,
it says in the manual for docker compose CE: "Download the new image, stop the old docker container, modify the Seafile image version in docker-compose.yml to the new version." 

In my docker-compose.yml I have
```
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile

```
so I am a little at loss how I should upgrade to the next version of seafile in this case. 

Or do I need to upgrade from 'inside' the docker image? I am trying to get from seafile sever 9 -> 10 -> 11

Thank you very much for clarifying this.

**Comment by freeplant** [comment]
You can change the string latest to a specific version you want to upgrade too.

**Comment by vincentkersten** [comment]
Thank you, Freeplant for the quick reply! 

For all not-so-dockerized ppl, head over to https://hub.docker.com/r/seafileltd/seafile-mc/tags
and choose the tag you want in your docker-compose file. Mine now reads:

  seafile:
    image: seafileltd/seafile-mc:10.0.1
    container_name: seafile


after docker-compose up -d it pulls the new image. Brilliant! 

Next I will got to update to the 11.x.x version. 
When that is done, I will revert the docker-compose file again to 


  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile


which will then keep me on the lastest 11 version of seafile. 


Big thanks to the seafile community :)
