### ISSUE TITLE
Notification server nginx configuration

### ISSUE THREAD

**Issue by veoco** [haiwen/seafile-admin-docs#314]
Current configuration:

https://github.com/haiwen/seafile-admin-docs/blob/03644e886995cea718197a0483267250da1d5b83/manual/deploy/notification-server.md?plain=1#L47-L67

It is incorrect because looking at [notification-server source code](https://github.com/haiwen/seafile-server/blob/master/notification-server/server.go#L252-L259):

```
r := mux.NewRouter()
r.Handle("/", appHandler(messageCB))
r.Handle("/events{slash:\\/?}", appHandler(eventCB))
r.Handle("/ping{slash:\\/?}", appHandler(pingCB))
```

The correct configuration should be:

```
map $http_upgrade $connection_upgrade {
default upgrade;
'' close;
}

server {
    location /notification {
        rewrite ^/notification(.*)$ $1 break;
        proxy_pass http://127.0.0.1:8083/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        access_log      /var/log/nginx/notif.access.log;
        error_log       /var/log/nginx/notif.error.log;
    }
}
```

**Comment by feiniks** [comment]
Hello @veoco , 
Since we have registered the path as “/”, we can establish a WebSocket connection directly via “/” without needing to rewrite the URL in Nginx. A rewrite should not be necessary.

**Comment by veoco** [comment]
@feiniks , if you don't rewrite the URL in nginx, it will be like this:

```
/notification/ping -> http://127.0.0.1:8083/notification/ping
/notification/ -> http://127.0.0.1:8083/notification/
```

After rewrite:

```
/notification/ping -> http://127.0.0.1:8083/ping
/notification/ -> http://127.0.0.1:8083/
```

And I just find seafile client's [request URL](https://github.com/haiwen/seafile/blob/303ef33146241dacbabfb7c20b9ca50e48e3512a/daemon/notif-mgr.c#L209) is also incorrect:

```
# current
/notification
# correct
/notification/
```

The configuration can truly work now is as follows:

```
map $http_upgrade $connection_upgrade {
default upgrade;
'' close;
}

server {
    location /notification {
        rewrite ^/notification/?(.*)$ /$1 break;
        proxy_pass http://127.0.0.1:8083/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        access_log      /var/log/nginx/notif.access.log;
        error_log       /var/log/nginx/notif.error.log;
    }
}
```

**Comment by feiniks** [comment]
Hello @veoco ,
the Nginx configuration will handle ping requests by forwarding them to the non-notification interface, while notification requests will be forwarded directly.

**Comment by veoco** [comment]
@feiniks ,Thank you for your explanation. I eventually realized that I was mistaken.
