### ISSUE TITLE
strange dependency requirements

### ISSUE THREAD

**Issue by Scottpedia** [haiwen/seafile-admin-docs#33]
I was installing seafile 8 on debian9 just now and one of the installation command specifies the version for sqlalchemy to install, as 1.4.3. And then I checked sqlalchemy's official website, which only has announced the release of 1.4.2. I don't know if anybody else is also experiencing this problem. 

Also why doesn't recent versions of seafile support debian 9? Can I still have a successful installation on a debian9 OS?

**Comment by dada-dudu** [comment]
SQLAlchemy 1.4.3 was released on March 25, 2021 according to https://pypi.org/project/SQLAlchemy/#history and https://www.sqlalchemy.org/blog/page/4/. I think you are alone with this problem ;-)

I don't have any experience with Debian 9. But I have installed Seafile 7 on Ubuntu 16.04 and Ubuntu 18.04. So Debian 9 should work just fine.

**Comment by Scottpedia** [comment]
@dada-dudu 

Yeah you are right. I was mistaken. Thanks for you reply tho.
