### ISSUE TITLE
Installing prerequisites for Seafile 9.0.x on Ubuntu 20.04

### ISSUE THREAD

**Issue by senior-web-engineer** [haiwen/seafile-admin-docs#344]
pip3 install command should be like the following.

`sudo pip3 install --timeout=3600 django==3.2.* future==0.18.* mysqlclient pymysql Pillow==9.4.0 pylibmc captcha jinja2 sqlalchemy==1.4.3 psd-tools django-pylibmc django-simple-captcha pycryptodome==3.12.0 cffi==1.14.0 lxml`

**Comment by freeplant** [comment]
The dependency of packages may need to be updated as the packages in operating system updated over the years. The best way is to use a docker image.
