### ISSUE TITLE
Enabling HTTPS with Nginx - needs epel-release

### ISSUE THREAD

**Issue by munrobasher** [haiwen/seafile-admin-docs#52]
In the documentation on this page:

[https://manual.seafile.com/deploy/https_with_nginx/](https://manual.seafile.com/deploy/https_with_nginx/)

It refers to installing nginx using:

`sudo yum install nginx -y`

On a clean install of Centos, this will fail as you first need to install epel-release:

`sudo yum -y install epel-release`

**Comment by freeplant** [comment]
Thanks. CentOS is no longer officially supported by Seafile. We will not update the manual.

**Comment by munrobasher** [comment]
Perplexed why seafile-pro-server_11.0.4_x86-64_CentOS.tar.gz was released last month if not supported?

**Comment by freeplant** [comment]
>  Plus this post was made 2.5 years ago when I believe it was.

At that time, I was not actively checking Github issues. I'm changing the way how I use GitHub and cleaning old issues right now.

> Perplexed why seafile-pro-server_11.0.4_x86-64_CentOS.tar.gz was released last month if not supported?

A good catch. We now officially only support Docker based method (preferred) and Ubuntu. For CentOS, we still upload the binary packages for some customers that not willing to change. But it is likely to be dropped when all the customers swithing to Docker based deployment.
