### ISSUE TITLE
Pin-point scipy Python module to versions <= 1.7.1

### ISSUE THREAD

**Issue by dleidert** [haiwen/seafile-admin-docs#57]
I recently discovered, that when I tried to install the Python modules for the professional edition using pip, the `psd-tools` module was pulling in `scipy` 1.7.3, which then was looking for the whole BLAS/LAPACK toolchain and then failing e.g. on Debian Buster. This problem did not exist with `scipy` 1.7.1 (it probably comes with some pre-compiled libraries). The toolchain, this latest release of the `scipy` module requires, is probably too much for an older system. Maybe you should document this in your installation instructions and stick with version 1.7.1. Otherwise, you'll have to document how to install all these prerequisites too.

**Comment by freeplant** [comment]
It should be outdated now.
