### ISSUE TITLE
Mention "new" memcached backend in upgrade notes

### ISSUE THREAD

**Issue by levinuss** [haiwen/seafile-admin-docs#59]
Hey,
after upgrading to 9.0.2 from 8.0.7 I had problems with memcached, because I was using a very old backend  (MemcachedCache) which was probably recommended in some old seafile manual. It worked until now but I guess the new django version doesnt like the old backend and it didn't work. 
Maybe this was addressed in some kind of upgrade notes or message before and I'm a fool for not reading it but if it wasn't I would be happy if this could be mentioned in the upgrade notes for version 9 to maybe save other people the hustle. Also, the upgrade notes should be linked from the changelog, like the upgrade notes from 8.x.x are for better visibility :)
Greetings,
Levin

**Comment by freeplant** [comment]
The document has been updated quite a lot recently. The issue should be not relevant anymore.
