### ISSUE TITLE
Missing/incorrect dependencies for Debian 11

### ISSUE THREAD

**Issue by Ailothaen** [haiwen/seafile-admin-docs#70]
Hello,

I just managed to install Seafile 9 on a Debian 11 system.

Everything went quite smoothly, however I had to correct some system dependencies:

- adding `libffi-dev`
- replacing `libmysqlclient-dev` by `libmariadb-dev-compat` (there is a version without the `-compat`, unsure about what would be the "most correct" to use)

Signalling therefore them in that issue so the docs can be updated.

**Comment by bertvandepoel** [comment]
I just tried to install on a fresh install, and this also requires python3-dev and libmemcached-dev to be able to run the pip command.

**Comment by mainboarder** [comment]
@bertvandepoel PR is here https://github.com/haiwen/seafile-admin-docs/pull/99

**Comment by bertvandepoel** [comment]
Thanks! I wish this would get merged. It has been setting there for months, weird!

**Comment by mainboarder** [comment]
As debian 11 is not officially [supported](https://cloud.seatable.io/dtable/external-links/a85d4221e41344c19566/?tid=0000&vid=0000) but planned within seafile version 9 (look at the tab features), I guess there is something going on (or nothing at all). Debian 11 is not a fresh version and Ubuntu 22.04 also.
I am afraid they might drop this planned feature as there is the docker alternative.
The docker container works with ubuntu, so the ubuntu 22.04 support is more realistic as debian 11 I think.
